Release 3.2.0
checkout/frames-ios pull request #32
Opened 2021-01-08 17:39 UTC by daven-gomes-cko

## Proposed changes

Release 3.2.0 with a new `NetworkError` enum and new methods.

## Types of changes

What types of changes does your code introduce to Frames Ios?
_Put an `x` in the boxes that apply_

* [X] Bugfix (non-breaking change which fixes an issue)
* [X] New feature (non-breaking change which adds functionality)
* [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

* [X] Lint and unit tests pass locally with my changes
* [X] I have added tests that prove my fix is effective or that my feature works
* [X] I have added necessary documentation (if appropriate)

2021-01-08 17:39 UTC, daven-gomes-cko commented
@deepesh-vasthimal-cko To be merged after https://github.com/checkout/frames-ios/pull/30

2021-01-11 10:16 UTC, nicolas-maalouf-cko approved these changes

2021-01-11 10:22 UTC, deepesh-vasthimal-cko commented
@daven-gomes-cko Your other PR which is https://github.com/checkout/frames-ios/pull/30 has more updated changes do you want to merge that and then update this PR to get latest ?

2021-01-11 10:23 UTC, deepesh-vasthimal-cko requested changes
Your other PR which is #30 has more updated changes do you want to merge that and then update this PR to get latest ?

2021-01-11 10:29 UTC, deepesh-vasthimal-cko commented on Source/CheckoutAPIClient.swift
> +                        let cardTokenResponse = try decoder.decode(CkoCardTokenResponse.self, from: response.data!)
I remember you fixed all these force unwraps in other PR. Not sure why are they not reflecting here ? . Can you please check.

2021-01-11 10:30 UTC, deepesh-vasthimal-cko commented on Source/CheckoutAPIClient.swift
> +                        let networkError = try decoder.decode(NetworkError.self, from: response.data!)
one more here : I remember you fixed all these force unwraps in other PR. Not sure why are they not reflecting here ? . Can you please check.

2021-01-11 10:31 UTC, deepesh-vasthimal-cko commented on Source/CheckoutAPIClient.swift
> +        var urlRequest = try! URLRequest(url: URL(string: url)!, method: HTTPMethod.post, headers: headers)
one more : I remember you fixed all these force unwraps in other PR. Not sure why are they not reflecting here ? . Can you please check.

2021-01-11 10:31 UTC, closed without merging