[Frames-iOS] - Allow billing address to be disabled on the prebuilt UI
checkout/frames-ios pull request #503
Opened 2024-01-12 14:41 UTC by aashna-narula-cko

## Issue
An SDK integrator is able to disable the billing address on the prebuilt UI. Currently they can only do this via the customisable UIs. When they disable the billing address, it doesn’t show on the prebuilt UI

_Issue ticket number and link._
[PIMOB-2358](https://checkout.atlassian.net/browse/PIMOB-2358)

## Proposed changes
Make billingFormStyle optional which will be checked against while creating default views.

## Test Steps

_If there's any functionality change, please list a step by step guide of how to verify the changes, and/or upload a screen recording for any visible changes._

> For instance:
> 1. Go to the main screen
> 2. Tap on Default
> 3. Verify the billing address view is removed

![Simulator Screenshot - iPhone 15 Pro - 2024-01-12 at 14 39 58](https://github.com/checkout/frames-ios/assets/156112796/daa948c5-ed6a-48e5-b35e-70abbe2a79ad)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

* [ ] Reviewers assigned
* [ ] I have performed a self-review of my code and manual testing
* [ ] Lint and unit tests pass locally with my changes
* [ ] I have added tests that prove my fix is effective or that my feature works
* [ ] I have added necessary documentation (if applicable)

## Further comments

_If this is a relatively large or complex change, kick off the discussion by explaining why you choose the solution you did and what alternatives you considered, etc..._

2024-01-16 10:12 UTC, aashna-narula-cko commented
These changes are no more required as there is already code to hide the billing address in Default; hence, closing this PR.

2024-01-18 12:43 UTC, okhan-okbay-cko approved these changes
⭐

2024-01-18 12:44 UTC, okhan-okbay-cko requested changes
1 sec

2024-01-18 14:14 UTC, okhan-okbay-cko approved these changes
🖊️

2024-01-18 14:17 UTC, okhan-okbay-cko requested changes
- UI Tests are being run on the already released Frames v 4.3.0
- Sample apps are being built on the same

We need to be sure to run them on the new code that's being provided with this PR. The way to do it is to fetch the SPM package from `aashna/PIMOB-2358-disable_billing_address`.

2024-01-18 16:05 UTC, okhan-okbay-cko approved these changes

2024-01-18 16:24 UTC, merged